In [1]:
import numpy as np  

In [21]:
X_data = np.random.randint(0, 10, (10, 8))

idx = np.random.choice(len(X_data), 2, replace=False)
x = X_data[idx]


In [22]:
x

array([[8, 2, 4, 3, 6, 7, 3, 9],
       [4, 1, 9, 8, 2, 1, 7, 3]])

In [17]:
X_data

array([[1, 6, 1, 9, 9, 2, 9, 0],
       [9, 6, 5, 0, 2, 1, 6, 4],
       [5, 4, 1, 7, 3, 6, 2, 7],
       [1, 2, 3, 7, 6, 5, 9, 9],
       [0, 2, 1, 9, 6, 5, 7, 2],
       [5, 2, 0, 7, 5, 0, 7, 6],
       [8, 3, 6, 5, 3, 9, 0, 1],
       [7, 3, 8, 5, 7, 4, 5, 6],
       [1, 3, 5, 5, 7, 1, 3, 0],
       [9, 5, 6, 7, 6, 6, 0, 8]])

In [14]:
dummy_input = np.random.randint(0, 10, (2, 8))
dummy_input

array([[3, 5, 6, 2, 4, 8, 7, 7],
       [6, 0, 2, 7, 2, 2, 5, 8]])

In [6]:
import os
import sys
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), "..")))

In [7]:
from core.tensor import Tensor
import numpy as np
import os

In [18]:
class EmbeddingLayer:
    def __init__(self, vocab_size, hidden_dim):
        self.weight = Tensor(np.random.randn(vocab_size, hidden_dim), requires_grad=True)

    def __call__(self, input_ids: np.ndarray) -> Tensor:
        # input_ids can be a Tensor or a numpy int array
        return Tensor(np.take(self.weight.data, input_ids, axis=0), requires_grad=True)

    def parameters(self):
        return [self.weight]


In [19]:
emb = EmbeddingLayer(vocab_size=10, hidden_dim=8)
emb.weight.data
emb

In [20]:
id = np.array([[1,4],[3,2]], dtype = np.int32)
id

array([[1, 4],
       [3, 2]])

In [21]:
id.reshape(-1)

array([1, 4, 3, 2])

In [42]:
emb.weight.gather(1, 1).data

AttributeError: 'NoneType' object has no attribute 'data'

In [28]:
emb.weight.data

array([[ 0.42705875, -1.83222039, -0.68135486,  0.09278092,  0.17859257,
         0.03048416, -1.17680119, -0.80175523],
       [ 0.06731017,  1.10336124,  1.51124749,  0.86604303,  0.32573859,
         0.09382551,  1.31097907,  0.68986266],
       [-1.20165219,  0.48093064,  0.50756281,  0.57713281, -0.39337005,
        -2.41465751, -2.52722941,  1.60977174],
       [ 0.3052633 , -0.26723335, -1.80289223, -1.0857104 ,  0.28418206,
        -0.44675944,  0.07719691, -0.08440967],
       [ 0.54695504,  1.07843795, -0.24294908, -1.11703216, -0.29597079,
        -0.36355226, -1.82647105, -1.87978453],
       [ 0.06728855,  0.15455863, -1.51974469,  2.16044559,  0.11665743,
        -0.8211282 , -0.95523661, -0.19135405],
       [ 1.63803273, -1.07662567, -0.86653662, -0.17761856, -0.34460021,
         0.58789151,  1.22239842,  2.00892166],
       [-0.64414526, -1.4672004 , -0.4782096 , -0.50575537,  0.72023786,
         0.55350734, -0.16940651, -0.54805076],
       [-0.28635518, -0.26946255

In [53]:
weight = Tensor(np.random.randn(8,10), requires_grad=True)
weight.data

array([[-1.09516624,  1.46668509,  0.54910108,  0.01749627, -0.33857317,
        -0.14709036,  0.46534263, -1.10381369, -0.48424701, -1.39875322],
       [-1.39999725, -0.09341065,  1.19543641, -0.0209185 ,  0.44439755,
         0.54285321,  0.04707359, -1.10456076, -0.97585059, -0.7613373 ],
       [ 0.1686404 , -0.85512684,  0.18776137, -1.12628062, -0.49832751,
         0.10349496, -0.23673547,  0.83145844, -0.68500885,  1.1116461 ],
       [ 1.03409858,  0.70870937, -0.21351386, -1.10718639,  0.42441904,
         0.38545012,  0.09409895, -0.3076364 ,  1.10788471,  0.186884  ],
       [-0.19404417,  0.36332314,  0.84365509,  0.85451538, -1.09848272,
        -1.18965219, -0.07800824, -0.20571097,  0.68905897,  2.22512598],
       [ 0.40990001,  0.09041661, -2.78769081,  0.10255861, -0.15370072,
         0.98523815,  1.22221796, -1.66870401,  0.00309363,  0.75796169],
       [-0.40698782,  0.27406472,  0.84013884,  0.47924524,  2.23341565,
        -0.87469095,  1.01440587, -1.36530894

In [55]:
weight.data.max(axis =1)

array([1.46668509, 1.19543641, 1.1116461 , 1.10788471, 2.22512598,
       1.22221796, 2.23341565, 1.61582928])

# SPM

In [1]:
import sentencepiece as spm


In [2]:
spm = spm.SentencePieceProcessor()

In [3]:
spm.load(r"C:\projects\T5\data\spm_multitask.model")

True

In [4]:
spm.decode([12, 4, 12, 8, 55, 49, 74, 12, 19, 44, 14])

'<translate> <lang:hi> I love you.'

In [12]:
spm.decode([12, 4, 12, 9, 55, 49, 74, 12, 19, 44, 14])

'<translate> <lang:es> I love you.'

# english to hindi dataset

In [ ]:
from datasets import load_dataset

# Load IITB dataset
ds = load_dataset("cfilt/iitb-english-hindi", split="train")

print("Example pairs (first 5):")
for sample in ds.select(range(5)):
    print(sample)


Example pairs (first 5):
{'translation': {'en': 'Give your application an accessibility workout', 'hi': 'अपने अनुप्रयोग को पहुंचनीयता व्यायाम का लाभ दें'}}
{'translation': {'en': 'Accerciser Accessibility Explorer', 'hi': 'एक्सेर्साइसर पहुंचनीयता अन्वेषक'}}
{'translation': {'en': 'The default plugin layout for the bottom panel', 'hi': 'निचले पटल के लिए डिफोल्ट प्लग-इन खाका'}}
{'translation': {'en': 'The default plugin layout for the top panel', 'hi': 'ऊपरी पटल के लिए डिफोल्ट प्लग-इन खाका'}}
{'translation': {'en': 'A list of plugins that are disabled by default', 'hi': 'उन प्लग-इनों की सूची जिन्हें डिफोल्ट रूप से निष्क्रिय किया गया है'}}


In [ ]:
import sentencepiece as spm

spm = spm.SentencePieceProcessor(r"C:\projects\T5\data\spm_multitask.model")


OSError: Not found: "./data/spm_multitask.model": No such file or directory Error #2